### ISSUE TITLE
Error: Not connected to message bus

### ISSUE THREAD

**Issue by leonbagdag** [gitpod-io/gitpod#1112]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by gleehokie** [comment]
I'm seeing the same:

Request startWorkspace failed with message: Not connected to message bus

**Comment by MichaelDHarris** [comment]
@jankeromnes @JesterOrNot

**Comment by JesterOrNot** [comment]
Can you send some debugging information from dev-tools console?

**Comment by MichaelDHarris** [comment]
@JesterOrNot We can't open the workspace to get to the dev-tool console. Everything stops at the loading page with an error message and turns the gitpod logo red.

**Comment by JesterOrNot** [comment]
I was able to reproduce the issue
![image](https://user-images.githubusercontent.com/50386709/72666268-1ec17180-39d6-11ea-9c02-1ab8ee2da0bb.png)

**Comment by MichaelDHarris** [comment]
@JesterOrNot this is the exact issue

**Comment by JesterOrNot** [comment]
Contacting team now!

**Comment by jankeromnes** [comment]
Thank you for reporting this. Duplicate of #1110 and should work again.

**Comment by MichaelDHarris** [comment]
Confirmation that the issue is resolved. Thank you.

**Comment by oswaldojerezz** [comment]
![image](https://user-images.githubusercontent.com/48268734/112167777-59183700-8bb6-11eb-906e-01f60bc88d9c.png)
This issue is still up

**Comment by literal-line** [comment]
I'm having the same issue too

**Comment by delucca** [comment]
It looks like Gitpod crashed :(

**Comment by AlessioToniolo** [comment]
Yeah I have the same issue, and I thought that it was a free trial/overused hours on gitpod.
