### ISSUE TITLE
gitpod not opening on any repository

### ISSUE THREAD

**Issue by Swastyy** [gitpod-io/gitpod#12128]
### Bug description

Hi community, the gitpod is not opening for me in any of the forks and showing `channel has been shut down`
Here's the screenshot: 
![image](https://user-images.githubusercontent.com/64654203/184589017-e3fb1df9-4908-4f36-ba9a-6ee072889463.png)

### Steps to reproduce

try opening it on my fork https://github.com/Swastyy/Books

**Comment by sankara-sabapathy** [comment]
++++ Struck here....
![image](https://user-images.githubusercontent.com/50690238/184589868-312804b3-ee46-4ad9-afbb-8b555e6e931c.png)

**Comment by PlengNakdee** [comment]
Also stuck at preparing

**Comment by Nash171** [comment]
Yes. Same issue!

**Comment by namdien177** [comment]
Still having this issue

**Comment by namdien177** [comment]
> Still having this issue

it seems like choosing to create a completely new workspace will work. However it will discard all changes on current workspace.

**Comment by AlexTugarev** [comment]
👋🏻 Hi! 
We're really sorry about that! 

There was an incident on US cluster, which got resolved by now. https://www.gitpodstatus.com/incidents/c57h9b3tzz86

Workspace should start now as expected!

**Comment by ditsuke** [comment]
@AlexTugarev I think there might be a problem still. My workspace[1] is stuck on "allocating resources"
![image](https://user-images.githubusercontent.com/72784348/184618568-526a3f2b-6822-43a4-a84d-8fe91b0b8e19.png)


[1]: https://gitpod.io/start/#ditsuke-rustlings-n0yvvtot372

**Comment by Nash171** [comment]
Seems issue is still there. I created all the workspaces got stucked. Now I can't start a new workspace either.
getting a error dialog saying

```
Limit Reached

You have reached the limit of parallel running workspaces for your account.
Please, upgrade or stop one of the running workspaces.
```
seems deleted workspaces are not destroyed correctly 😢

**Comment by minmoong** [comment]
Same issue..😥
![캡처4](https://user-images.githubusercontent.com/62737839/184620358-dbf3aea3-0b77-4216-9a27-cda0b601a92e.PNG)
but
![캡처5](https://user-images.githubusercontent.com/62737839/184620372-0f3ad961-d85b-4dd0-b961-4c4cbe823ca2.PNG)

**Comment by svenefftinge** [comment]
The bogus workspace states are now fixed.

**Comment by Swastyy** [comment]
@svenefftinge thanks, its working now. 😄
