### ISSUE TITLE
Cannot open in VSCode on macOS 13 beta, getting a `certificate has expired` error

### ISSUE THREAD

**Issue by allezxandre** [gitpod-io/gitpod#13019]
### Bug description

After starting a Gitpod Workspace, I am able to use the workspace from the browser, but trying to open it in VSCode Desktop fails, the logs read:

```
[Info  - 16:40:30.702] gitpod.gitpod-desktop/0.0.58 (22.1.0 darwin arm64) vscode/1.71.1 (Visual Studio Code)
[Info  - 16:40:30.706] Started authentication provider for https://gitpod.io/
[Info  - 16:40:30.706] Reading sessions from keychain...
[Trace  - 16:40:30.895] Token acquired from secret storage.
[Info  - 16:40:30.900] Got stored sessions!
[Info  - 16:40:31.58] Verified session with the following scopes: function:getLoggedInUser function:getOwnerToken function:getSSHPublicKeys function:getWorkspace function:sendHeartBeat resource:default
[Trace  - 16:40:31.58] Read the following session from the keychain with the following scopes: function:getLoggedInUser function:getOwnerToken function:getSSHPublicKeys function:getWorkspace function:sendHeartBeat resource:default
[Info  - 16:40:31.62] Verified session with the following scopes: function:getLoggedInUser function:getOwnerToken function:getWorkspace resource:default
[Trace  - 16:40:31.62] Read the following session from the keychain with the following scopes: function:getLoggedInUser function:getOwnerToken function:getWorkspace resource:default
[Info  - 16:40:31.62] Got 2 verified sessions.
[Info  - 16:40:31.83] Getting sessions for function:getLoggedInUser,function:getOwnerToken,function:getSSHPublicKeys,function:getWorkspace,function:sendHeartBeat,resource:default...
[Info  - 16:40:31.83] Got 1 sessions for function:getLoggedInUser,function:getOwnerToken,function:getSSHPublicKeys,function:getWorkspace,function:sendHeartBeat,resource:default...
[Info  - 16:40:31.86] Opening Gitpod workspace
vscode://gitpod.gitpod-desktop/workspace/gitpod/gitpod-ws.code-workspace?<redacted>
[Error  - 16:40:31.390] Failed to connect to gitpodio-<workspace-id-here> Gitpod workspace:
FetchError: request to https://<workspace-id-here>.gitpod.io/_ssh/host_keys failed, reason: certificate has expired
    at ClientRequest.<anonymous> (<my-home>/.vscode/extensions/gitpod.gitpod-desktop-0.0.58/node_modules/node-fetch/lib/index.mjs:1485:11)
    at ClientRequest.emit (node:events:538:35)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

https://user-images.githubusercontent.com/39482679/190467685-23304b93-b91e-4753-9de0-7c9cbb889aff.mp4

### Steps to reproduce

Go to any workspace (<https://gitpod.io/#https://github.com/gitpod-io/gitpod>), open in VSCode (Desktop), VSCode errors out

### Anything else?

As the only thing I've done recently is upgrade to macOS 13 Beta, this might have to do with some root SSL Certificate changes introduced by the OS upgrade. It might also be a recent Homebrew package upgrade that I have probably  performed recently.

Discord thread: https://discord.com/channels/816244985187008514/1020003575390285894

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3qudm)

**Comment by axonasif** [comment]
Hey @allezxandre, could you grab the logs zip by following [this](https://www.gitpod.io/docs/troubleshooting#gitpod-logs-in-vs-code-web-and-desktop)? You can use this issue link as a reference on the email then.

**Comment by allezxandre** [comment]
> could you also grab the logs zip by following [this](https://www.gitpod.io/docs/troubleshooting#gitpod-logs-in-vs-code-web-and-desktop)?

Sent 📬 , thanks

**Comment by akosyakov** [comment]
This error is from Node.js and was fixed in recent versions. You should upgrade to latest VS Code.

**Comment by akosyakov** [comment]
@iQQBot Could it be that some certificates expired on the system level? Do you know how one can troubleshoot it?

**Comment by allezxandre** [comment]
Yes I am already running the latest version. Here's my VSCode about:

```
Version: 1.71.2 (Universal)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

(My VSCode auto-upgraded from 1.71.1 to 1.71.2 earlier today, but the issue is still present. This issue also happens running on a fresh install of VSCode Insiders)

**Comment by allezxandre** [comment]
After some investigation, the issue appears to be VSCode-related, as using `node-fetch` on the same URLs from the Node REPL does not error.

As a temporary fix I found in https://github.com/microsoft/vscode/issues/136787#issuecomment-968771447, I set the following setting in VSCode and Gitpod works again after a reload:

```json
"http.systemCertificates": false
```

**Comment by akosyakov** [comment]
@allezxandre thank you, we also do some improvements on our side, but it is a great hint, we could document it and point out via a notification if it happens

**Comment by akosyakov** [comment]
@jeanp413 @mustard-mh @loujaybee I think we should document a work around in https://github.com/gitpod-io/gitpod/issues/13019#issuecomment-1249287909
