### ISSUE TITLE
Cannot build workspace iamge: non-zero code: 100

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#1439]
### Describe the bug

I have a customized Docker image for GitPod. It has been working well for a long time but recently I got the following error message. Does anyone know what might have caused the issue?
```
Error: build failed: cannot build workspace image: The command '/bin/sh -c /var/gitpod/layer.sh     && rm -f /var/gitpod/layer.sh' returned a non-zero code: 100
```
### Steps to reproduce
1. Go to https://gitpod.io/#https://github.com/dclong/blog
2. The error message will show up after a while (after failing to build the image).

### Expected behavior
The customized image used to work, so I expect it continue to work. If changes required, there should be a way to let users know.

**Comment by jankeromnes** [comment]
Oh. Many thanks @dclong for reporting this bug. I recently modified the Gitpod layer, but didn't expect this could break anything. Sorry!

I was able to reproduce your issue:

<img width="1178" alt="Screenshot 2020-04-24 at 09 56 58" src="https://user-images.githubusercontent.com/599268/80188901-1ea6c280-8612-11ea-8528-7d4c8f1c5b8a.png">

Will investigate and try to fix as soon as possible.

**Comment by dclong** [comment]
Any update on this issue?

**Comment by Kreyren** [comment]
Checking..

**Comment by Kreyren** [comment]
Works for me:

<details>
<summary>Output</summary>

```
sha256:b7b31b7ce275e7740bd683d00a15fa511218a6d6c7b0357c3f8469739a5d35ec: Pulling from dclong/gitpod
cbdc015de259: Already exists
35f8707632bb: Already exists
6b786d087f83: Already exists
31fb3cd05fdd: Already exists
9d33ffd2d0c7: Pulling fs layer
2f06521c5e0d: Pulling fs layer
8469ea066db4: Pulling fs layer
37f4791ba346: Pulling fs layer
d6480fb60bdc: Pulling fs layer
bc7262b9512d: Pulling fs layer
503ff2f462df: Pulling fs layer
f0b1ca8a070c: Pulling fs layer
a02408ecc6bc: Pulling fs layer
24fcd5b05493: Pulling fs layer
5e9863a0b6a7: Pulling fs layer
f0d2cd7dac40: Pulling fs layer
ccb2ef3d6fc7: Pulling fs layer
837393a1d877: Pulling fs layer
f4f113819ef3: Pulling fs layer
2988a6ab75c6: Pulling fs layer
7a41d74be894: Pulling fs layer
25922d7ef037: Pulling fs layer
17f8c153e2a7: Pulling fs layer
c5b677fc29e0: Pulling fs layer
3d22411d1624: Pulling fs layer
69680cb260c0: Pulling fs layer
8a4ce02bc0dc: Pulling fs layer
9e18afb11a8c: Pulling fs layer
7b246e450b53: Pulling fs layer
7ea6bd4c8c23: Pulling fs layer
48195d871752: Pulling fs layer
ae68780b64c8: Pulling fs layer
beab5b571cb9: Pulling fs layer
14ca714941b1: Pulling fs layer
9f848bfcfe80: Pulling fs layer
37f4791ba346: Waiting
d6480fb60bdc: Waiting
bc7262b9512d: Waiting
25922d7ef037: Waiting
503ff2f462df: Waiting
f0b1ca8a070c: Waiting
17f8c153e2a7: Waiting
a02408ecc6bc: Waiting
c5b677fc29e0: Waiting
24fcd5b05493: Waiting
5e9863a0b6a7: Waiting
3d22411d1624: Waiting
f0d2cd7dac40: Waiting
69680cb260c0: Waiting
ccb2ef3d6fc7: Waiting
ae68780b64c8: Waiting
837393a1d877: Waiting
f4f113819ef3: Waiting
8a4ce02bc0dc: Waiting
beab5b571cb9: Waiting
2988a6ab75c6: Waiting
7a41d74be894: Waiting
9e18afb11a8c: Waiting
14ca714941b1: Waiting
9f848bfcfe80: Waiting
7b246e450b53: Waiting
48195d871752: Waiting
7ea6bd4c8c23: Waiting
2f06521c5e0d: Download complete
8469ea066db4: Download complete
37f4791ba346: Verifying Checksum
37f4791ba346: Download complete
d6480fb60bdc: Verifying Checksum
d6480fb60bdc: Download complete
503ff2f462df: Verifying Checksum
503ff2f462df: Download complete
f0b1ca8a070c: Verifying Checksum
f0b1ca8a070c: Download complete
9d33ffd2d0c7: Verifying Checksum
9d33ffd2d0c7: Download complete
bc7262b9512d: Verifying Checksum
bc7262b9512d: Download complete
5e9863a0b6a7: Verifying Checksum
5e9863a0b6a7: Download complete
a02408ecc6bc: Verifying Checksum
a02408ecc6bc: Download complete
f0d2cd7dac40: Verifying Checksum
f0d2cd7dac40: Download complete
837393a1d877: Verifying Checksum
837393a1d877: Download complete
f4f113819ef3: Verifying Checksum
f4f113819ef3: Download complete
ccb2ef3d6fc7: Download complete
9d33ffd2d0c7: Pull complete
2f06521c5e0d: Pull complete
2988a6ab75c6: Download complete
8469ea066db4: Pull complete
37f4791ba346: Pull complete
d6480fb60bdc: Pull complete
25922d7ef037: Download complete
24fcd5b05493: Download complete
bc7262b9512d: Pull complete
c5b677fc29e0: Verifying Checksum
c5b677fc29e0: Download complete
503ff2f462df: Pull complete
f0b1ca8a070c: Pull complete
a02408ecc6bc: Pull complete
17f8c153e2a7: Verifying Checksum
17f8c153e2a7: Download complete
7a41d74be894: Verifying Checksum
7a41d74be894: Download complete
3d22411d1624: Verifying Checksum
3d22411d1624: Download complete
69680cb260c0: Verifying Checksum
69680cb260c0: Download complete
7b246e450b53: Verifying Checksum
7b246e450b53: Download complete
7ea6bd4c8c23: Verifying Checksum
7ea6bd4c8c23: Download complete
48195d871752: Verifying Checksum
48195d871752: Download complete
ae68780b64c8: Verifying Checksum
ae68780b64c8: Download complete
beab5b571cb9: Verifying Checksum
beab5b571cb9: Download complete
8a4ce02bc0dc: Verifying Checksum
8a4ce02bc0dc: Download complete
14ca714941b1: Verifying Checksum
14ca714941b1: Download complete
24fcd5b05493: Pull complete
5e9863a0b6a7: Pull complete
f0d2cd7dac40: Pull complete
9f848bfcfe80: Verifying Checksum
9f848bfcfe80: Download complete
ccb2ef3d6fc7: Pull complete
837393a1d877: Pull complete
f4f113819ef3: Pull complete
2988a6ab75c6: Pull complete
9e18afb11a8c: Verifying Checksum
7a41d74be894: Pull complete
25922d7ef037: Pull complete
17f8c153e2a7: Pull complete
c5b677fc29e0: Pull complete
3d22411d1624: Pull complete
69680cb260c0: Pull complete
8a4ce02bc0dc: Pull complete
9e18afb11a8c: Pull complete
7b246e450b53: Pull complete
7ea6bd4c8c23: Pull complete
48195d871752: Pull complete
ae68780b64c8: Pull complete
beab5b571cb9: Pull complete
14ca714941b1: Pull complete
9f848bfcfe80: Pull complete
Digest: sha256:b7b31b7ce275e7740bd683d00a15fa511218a6d6c7b0357c3f8469739a5d35ec
Status: Downloaded newer image for dclong/gitpod@sha256:b7b31b7ce275e7740bd683d00a15fa511218a6d6c7b0357c3f8469739a5d35ec
adding Gitpod layer
..
..
..
..
..
..
..
..
..
.pushing workspace image
..
..
..
..
..
..
..
..
..
.
```

</details>

@dclong Can you elaborate on what is the issue?

**Comment by dclong** [comment]
@Kreyren Thank you for the update! I just tried and it's actually working now. Didn't work for me yesterday. So glad that the issue is fixed!

**Comment by Kreyren** [comment]
@dclong great ^-^ sorry for taking so long!

**Comment by randomserver** [comment]
BUMP still seeing this issue on

https://gitpod.io/#https://github.com/randomserver/distributed-process-cluster

using a custom image based on fpco/stack-build

**Comment by elheck** [comment]
@jankeromnes or  @Kreyren can you reopen this issue?
The same behavior still exists for me as well. 
The exact same configuration used to work for https://gitpod.io/#https://github.com/Squiddrone/Squiddrone.
I also use a custom image based on ubuntu 19.10.
