### ISSUE TITLE
Ports stuck at detecting

### ISSUE THREAD

**Issue by DataCleansingEnthusiast** [gitpod-io/gitpod#17446]
### Bug description

Ports stuck at detecting...
I am a paid customer of gitpod. From past 24 hours, when I try to run docker compose up to bring up my application I get Ports stuck at detecting. I tried to change the ports to a different number and tested. It worked, but when I commited the code and opened the workspace and I have the same error.
I am in US region. Please help
Thanks

### Steps to reproduce

1. open new gitpod workspace from github
2. docker-compose up
3. Ports are stuck at detecting

### Expected behavior

<img width="554" alt="image" src="https://user-images.githubusercontent.com/6144110/235311205-83c30128-0fd8-4869-ac94-b2cd4d637752.png">

### Example repository

<img width="620" alt="errconnect1" src="https://user-images.githubusercontent.com/6144110/235311123-a614fe94-a85f-47e7-8bac-3e7dab94eaa7.PNG">

**Comment by axonasif** [comment]
Hi @DataCleansingEnthusiast, is this still happening?

**Comment by DataCleansingEnthusiast** [comment]
Yes, still happening from yesterday early morning PST.
Workspace ID          : datacleansi-awsbootcamp-f3y8veklrpt  
I just checked again 12.26 PM PST

**Comment by NsinghP** [comment]
I am suffering from same problem. It has been over 24 hours now. Please see the attached image on windows11/firefox:
![Screenshot (210)](https://user-images.githubusercontent.com/69470381/235466532-8d822159-524a-46c7-88b3-1fb87a0900c5.png)
and the "Ports" window shows "detecting" for port 3000.

**Comment by alesanchezr** [comment]
Yes this is happening since friday, all our students have the same issue, some times it gets fixed by running `gp ports expose <port number>` but then its impossible to make the ports public.

**Comment by axonasif** [comment]
@alesanchezr I think you're looking for `gp ports visibility <port>:public`.
- https://www.gitpod.io/docs/references/gitpod-cli#visibility

**Comment by cjensenius** [comment]
I'm seeing if others on the team can replicate this, on my workstation if I have the gitpod local companion app running (Windows 10) the ports do not become stuck in 'detecting...' state. I replicated this workaround three times, and confirmed that if I do not have the companion app running the issue manifests two times.

**Comment by mikenikles** [comment]
Still happening, for public ports only in our case. On cluster `ws-us96b`. At which point is this considered an issue and gets reported via https://www.gitpodstatus.com?

Looking at recent GitHub issues and the Questions in Discord, there have been a number of reports over the last few days.

**Comment by axonasif** [comment]
Hey folks, sorry about the issue you experienced, it was resolved a while back.

https://www.gitpodstatus.com/incidents/6h1gd447lk7b

All newly created workspaces should contain the fix.

**Comment by cjensenius** [comment]
@axonasif The ports issue persists after the fix, I have confirmed reports from other team members. I am personally observing the issue currently in a newly launched workspace (greenit-spower-s6tvc58lvcr.ws-us96b.gitpod.io)

![image](https://user-images.githubusercontent.com/1717750/235925278-6fa2f5f8-ea0b-460c-a4c1-1fea1581a53d.png)

If I have the local-app running (Windows 10), the issue is not triggered

**Comment by axonasif** [comment]
@cjensenius oops, please hold on a bit. There was a mismatch in our recent deployment an hour ago that bought it back. It should be fixed in our next deployment.

**Comment by axonasif** [comment]
@cjensenius a new deployment was made about 30 mins before, should be working again.
