### ISSUE TITLE
Unable to report issue from Code 

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2628]
### Steps to reproduce

1. Set Code as default editor on Gitpod User Settings. 
2. Open repo by using link https://gitpod.io/#https://github.com/vymarkov/nodejs-devops-extension-pack
3. Open command Palette and type `Repot issue` then select command `Help: Report issue`
4. Code will try open url that lead to https://github.com/akosyakov/gitpod-code/issues/new

### Expected behavior

I expect that I will be redirected to link https://github.com/gitpod-io/gitpod/issues/new?template=bug_report.md instead of https://github.com/akosyakov/gitpod-code/issues/new

### Additional information

![image](https://user-images.githubusercontent.com/1110697/103212466-83d65480-4913-11eb-9a0e-bc9d462a553d.png)

**Comment by svenefftinge** [comment]
fixed in https://github.com/gitpod-io/vscode/commit/d46707ec9d96e9b7af05baf5f3d5c2b9811ddb27

**Comment by vymarkov** [comment]
As I see from result command help: about fix is still not deployed, is it correct ?
