### ISSUE TITLE
TypeError: Cannot read property 'revive' of undefined

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3837]
We're seeing these two errors about half-a-million times since yesterday's deployment:

[error1](https://console.cloud.google.com/errors/CLX5kuDk9Zua_wE?time=P7D&project=gitpod-191109&organizationId=327752801919)
```
"TypeError: Cannot read property 'revive' of undefined
    at Array.e.replacer (https://<wsid>.ws-eu03.gitpod.io/bundle.js:19:775475)
    at JSON.stringify (<anonymous>)
    at Function.e.request (https://<wsid>.ws-eu03.gitpod.io/bundle.js:19:774728)
    at e.remoteCall (https://<wsid>.ws-eu03.gitpod.io/bundle.js:19:771820)
    at Proxy.n.<computed>.r.charCodeAt.n.<computed> (https://<wsid>.ws-eu03.gitpod.io/bundle.js:19:771204)
    at https://<wsid>.ws-eu03.gitpod.io/bundle.js:106:894364
    at https://<wsid>.ws-eu03.gitpod.io/bundle.js:1:118450
    at e.invoke (https://<wsid>.ws-eu03.gitpod.io/bundle.js:1:118668)
    at e.fire (https://<wsid>.ws-eu03.gitpod.io/bundle.js:1:120719)
    at https://<wsid>.ws-eu03.gitpod.io/bundle.js:86:555002" 
```

[error2](https://console.cloud.google.com/errors/CKHqg4Tl0NzsNA?time=P7D&project=gitpod-191109&organizationId=327752801919)
```
"TypeError: Cannot read property 'revive' of undefined
    at Object.e.replacer (https://<wsid>.ws-eu03.gitpod.io/bundle.js:19:775475)
    at JSON.stringify (<anonymous>)
    at Function.e.request (https://<wsid>.ws-eu03.gitpod.io/bundle.js:19:774728)
    at e.remoteCall (https://<wsid>.ws-eu03.gitpod.io/bundle.js:19:771820)
    at Proxy.n.<computed>.r.charCodeAt.n.<computed> (https://<wsid>.ws-eu03.gitpod.io/bundle.js:19:771204)
    at e.onDelta (https://<wsid>.ws-eu03.gitpod.io/bundle.js:160:606551)
    at e.callback (https://<wsid>.ws-eu03.gitpod.io/bundle.js:160:605056)
    at e.update (https://<wsid>.ws-eu03.gitpod.io/bundle.js:160:609785)
    at https://<wsid>.ws-eu03.gitpod.io/bundle.js:160:607938
    at https://<wsid>.ws-eu03.gitpod.io/bundle.js:1:118450" 
```

**Comment by akosyakov** [comment]
It should have been fixed by https://github.com/gitpod-io/gitpod/pull/3810.

**Comment by meysholdt** [comment]
I'm still seeing the error in prod even though we rolled out the fix two hours ago. I'm assuming the fix is only available in workspaces that started after the deployment. So let's leave this issue open until tomorrow and check agian then.

**Comment by JanKoehnlein** [comment]
Doesn't seem to happen anymore.
