### ISSUE TITLE
Don't make `gp` rely on PATH to look up `code`

### ISSUE THREAD

**Issue by pattacini** [gitpod-io/gitpod#3844]
This request originates from a [community post][1], where I described my use case foreseeing the possibility to launch a purposely installed version of `code` within a VNC desktop as in the screenshot below.

![abac653b7ac361ccd0cd125ec35bcd759675d442](https://user-images.githubusercontent.com/3738070/114019754-13729400-986f-11eb-9403-24f198a11aec.png)

The point is that to this end I had to [shadow in the `PATH` the version of `code`][2] installed by the Gitpod layer. The latter causes headaches when the VS Code UI is selected in Gitpod: for example, `gp open <filename>` clearly no longer works.

@akosyakov suggested that this could be solved by preventing `gp` from relying on `PATH` to look up `code`.

[1]: https://community.gitpod.io/t/gp-open-does-not-work-in-vs-code-ui/3172
[2]: https://github.com/vvv-school/vvv-school.github.io/blob/master/dockerfiles/gitpod/Dockerfile#L164

**Comment by akosyakov** [comment]
Here https://github.com/gitpod-io/gitpod/blob/7d934f6a3ec82f879692f37987b2f486707b3ade/components/ide/code/leeway.Dockerfile#L63-L68 we should replace `code` with `/ide/bin/code`. PRs are welcomed!

**Comment by pattacini** [comment]
PR opened in #3846.

**Comment by akosyakov** [comment]
fixed by https://github.com/gitpod-io/gitpod/pull/3846 we are going to deploy it tomorrow morning

**Comment by pattacini** [comment]
Hi @akosyakov 

I'm still getting `/ide/bin/code` as the output of `which code` on a fresh workspace, meaning that it's still in the PATH.

Do I need to wait longer for the deployment?

**Comment by akosyakov** [comment]
We did not fix shadowing of `code`, only you can do it, but `gp open` should delegate to Gitpod Code CLI. Does `gp open` work for you?

**Comment by pattacini** [comment]
Ok then! Let me try: I have to generate my docker images again.

**Comment by pattacini** [comment]
It works like a charm 👍🏻 
Thanks again!
