### ISSUE TITLE
[docker builds] keep showing the output on fail

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#423]
When a docker build fails we currently remove the terminal with all its helpful contents and replace it with a single error message usually saying something like:
<img width="1148" alt="Screenshot 2019-04-01 at 22 37 10" src="https://user-images.githubusercontent.com/372735/55358033-b64ce680-54ce-11e9-8e83-c1c9579e8f91.png">

We should keep the terminal output as it reveals pointers to where things went south first.

**Comment by jankeromnes** [comment]
This just bit me a few times, and makes it hard to iterate on Dockerfiles.

<img width="821" alt="Screenshot 2019-04-06 at 17 15 51" src="https://user-images.githubusercontent.com/599268/55671520-1ce85080-5891-11e9-987f-08c2526366a9.png">

**Comment by akosyakov** [comment]
We also don't report anything for prebuilt workspaces, it hangs in `Workspace prebuilt is starting...`.

**Comment by jankeromnes** [comment]
Current status: Trying to snap a screenshot at the exact millisecond when the error is printed in the Docker build log, just before the above screen shows up.

**Comment by svenefftinge** [comment]
fixed in production

**Comment by jankeromnes** [comment]
Seems like this error is back. I've had it this week and @anudeepreddy too.
