### ISSUE TITLE
can't connect server

### ISSUE THREAD

**Issue by wanghui5257** [gitpod-io/gitpod#470]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1677849/55926506-2f250e80-5c44-11e9-88dd-834456d25d92.png)

**Comment by svenefftinge** [comment]
This happens when the websocket connection gets blocked.

**Comment by svenefftinge** [comment]
Do you see that regularly or only occasionally?

**Comment by jankeromnes** [comment]
This appears to be a WebSocket rate-limit problem. We noticed it a while ago in Firefox, and reported it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1520153

We've also started noticing it in Chrome recently, and we believe that's caused by Chrome aligning with Firefox and the WebSocket specification regarding the top-level-domain-wide rate limit.

The problem is usually caused by a workspace tab that is still open, but the workspace itself is stopped. This causes the tab to "spam" the WebSocket connection, hitting the browser's rate limit for all of `*.gitpod.io`, and thus disrupting all other workspaces and the Gitpod dashboard in that browser.

The workaround is to close all stopped workspace tabs. This restores service pretty quickly.

We should also look into not being so aggressive on the WebSocket. @geropl suggested something like this:

> I suggest we try to fix this by detecting "stopped && tabInBackground" and stop reconnecting then. Only on "tabInForegroundAgain":
> - try to query the workspace state and if running, try to reconnect
> - repeat periodically (but more seldomly than now, maybe provide a button to try manually

**Comment by JesterOrNot** [comment]
this has happened to me when I have been on the move going on and offline again what were you doing when this occurred?

**Comment by svenefftinge** [comment]
Here's the related issue in chrome. It is fixed already and stable will hopefully be updated soon.
You can use canary in the meantime.
https://bugs.chromium.org/p/chromium/issues/detail?id=1006243

**Comment by Gilleece** [comment]
A year later and I'm having this issue on brave. I've closed all gitpod tabs but still can't access it again. It seems like going through a different browser fixes the problem, I've been using gitpod on brave without issue for a while now and I definitely didn't go offline.
