### ISSUE TITLE
Unable to build docker container using `docker build` and `docker-compose build`

### ISSUE THREAD

**Issue by danBamikiya** [gitpod-io/gitpod#5160]
### Bug description

I tried to build a container using `docker-compose build` and later using `docker build` but both methods resulted in an error:
```
Building server
Sending build context to Docker daemon    190kB

Step 1/8 : FROM node:14-slim AS server-dev
 ---> 85ef76a59eb1
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 14deb1432a70
Step 3/8 : COPY ./package*.json ./
 ---> Using cache
 ---> 837c029ec0b4
Step 4/8 : RUN npm i
 ---> Running in d21be111f2ec
OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "proc" to rootfs at "/proc" caused: operation not permitted: unknown
```

I tried using another workspace but both resulted in the same error.

### Steps to reproduce

Try to build a container image using `docker build` or `docker-compose build`.

### Expected behavior

It should build the images.

### Example repository

Its private.

**Comment by danBamikiya** [comment]
I was supposed to create this Issue some hours ago. But after getting busy with some other stuff and returning to create it, I checked for other related issues and found this issue #5124 which looks solved by this PR: #5139 so I'm closing this issue.

**Comment by danBamikiya** [comment]
My images now build as expected.

**Comment by wintercounter** [comment]
Unfortunately, I'm still having this issue.

```
OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted: unknown
```

`apk add` is where it fails.

```
FROM node:16-alpine

RUN apk add --update libtool automake gcc autoconf nasm libpng-dev pkgconfig python2 py-pip procps git g++ libc6-compat libjpeg-turbo-dev make
```

**Comment by danBamikiya** [comment]
@wintercounter try the workaround in [this comment](https://github.com/gitpod-io/gitpod/issues/5124#issuecomment-897048987)
