### ISSUE TITLE
Gitpod cannot integrate the Self-Hosted Gitlab with the port number

### ISSUE THREAD

**Issue by Gwzlchn** [gitpod-io/gitpod#5305]
### Bug description

The url of our self-hosted GitLab instance has a port number, which is not the usual 80/443, so when I integrate our GitLab into the GitPod SaaS platform, it prompts that the host name is invalid.

I found out the following regex will filters out urls with port numbers 
[components/server/src/workspace/gitpod-server-impl.ts#L1783](https://github.com/gitpod-io/gitpod/blob/34b420b5281e27017674f7c1edc31bb85717fbee/components/server/src/workspace/gitpod-server-impl.ts#L1783)

### Steps to reproduce

The figure below shows the situation.
![image](https://user-images.githubusercontent.com/23080717/130347834-a2789d3b-8157-4bf0-8ded-6714b1e7b737.png)

1. Open the page: https://gitpod.io/integrations
2. Click "New Intergration"
3. Input a GitLab url with the port number in "Provider Host Name" box
4. Prompts "Invalid host name."

### Expected behavior

Gitpod SaaS should support the Self-Hosted Gitlab with the port number

**Comment by gtsiolis** [comment]
Thanks for bringing this up, @VouDoo!

Let me reopen this and loop in a few folks from the corresponding team. Cc @geropl @jldec

**Comment by jldec** [comment]
Keep alive in WebApp project

**Comment by AlexTugarev** [comment]
I propose a more comprehensive solution to this by replacing the regex to validate the URI by actually ping the host (including path) of the gitlab installation. This way we can test connectivity between server and gitlab and report any issues, which from time to time is a big pita to debug remotely.

**Comment by jmls** [comment]
yeah we just hit this during a call with a prospective customer (embarrassing!)  - although we were using bitbucket.

We really need this fix! Please do not mark as "stale".

**Comment by lucasvaltl** [comment]
Changed title as this likely impacts both the SaaS and Self-Hosted versions of Gitpod. Ideally a fix applies to both :)

**Comment by AlexTugarev** [comment]
@lucasvaltl, any chance you could help testing https://github.com/gitpod-io/gitpod/pull/11409 with a proper setup, i.e. with unusual port?

**Comment by lucasvaltl** [comment]
@AlexTugarev - Let me ask the team on Slack - will cc you and then we can see what we can do :)

**Comment by AlexTugarev** [comment]
Fixed in https://github.com/gitpod-io/gitpod/pull/11409

**Comment by micszc** [comment]
HI, I'm still getting this error. I have updated gitpod to newest version -> 2022.6.1 and still there's error about Invalid host name.
What should I do to go further?

**Comment by MrSimonEmms** [comment]
Hi @micszc, this hasn't yet been released to the Self-Hosted version yet. It'll go out with the `2022.7.0` release, which is scheduled for around the 28th July.

**Comment by micszc** [comment]
Ok, thanks, sorry for being impatient :) I will wait for new release.

**Comment by jmls** [comment]
was this tried end-to-end ? We are getting errors on the initial auth 

![image](https://user-images.githubusercontent.com/929523/181504410-b8a863c3-a069-42a7-b719-9dc0636619c1.png)

**Comment by lucasvaltl** [comment]
Hey @jmls are you using the SaaS or Self-Hosted version of Gitpod? If it is the latter, Gitpod Self-Hosted version 2022.07, which includes this fix, was only released to those on the community license today :)

**Comment by jmls** [comment]
no, we're SaaS

**Comment by AlexTugarev** [comment]
@jmls! Thanks for reporting. Yes, that was [tested](https://github.com/gitpod-io/gitpod/pull/11409#pullrequestreview-1040291097), but there might be gaps. 

One question, because the error rendered is on GitLab, did you reuse the OAuth application on that instance, or did you create a new one? Please verify that redirect URI of the OAuth application also includes the port number, where the colon sign is replaced by an underscore, e.g. `gitlab.mydomain.com_8433`

**Comment by jmls** [comment]
we got the error in bitbucket - this happens on a new oauth application, and yes we did include the _port in the redirect uri (we copied it from the gitpod UI)

**Comment by AlexTugarev** [comment]
@jmls, I think I got it now! The Git Integration modal doesn't escape the `:`, thus you probably just copy and pasted the URI, which makes perfectly sense. 

<img width="493" alt="Screen Shot 2022-08-02 at 09 53 57" src="https://user-images.githubusercontent.com/914497/182322425-ebba1206-3f7c-41ae-83af-29ae2741746f.png">

🤦🏻 

The colon in the URI to be copy-pasted into your OAuth setting on GitLab/GHE/BBS should not contain the colon (`:`) it should be an underscore (`_`). 

I'll create a PR to fix the UI, but you can work around this, by fixing the URI in you OAuth application.
