### ISSUE TITLE
Terminal keyboard language/layout

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5460]
### Bug description

> Since Friday last week (27th August) our team’s terminals appear to be enforcing a US keyboard layout.
> 
> We’ve been using Gitpod for many months (the base image we use hasn’t changed) and usually don’t have any problems with typing in our GB keyboard layout.
> 
> Is anyone else outside the US experiencing this? It’s really frustrating - especially with quotes!

Originally reported here: https://community.gitpod.io/t/terminal-keyboard-language-layout/4852

Have not tried to reproduce yet.

### Steps to reproduce

Start a workspace with a non-US layout.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5460#issuecomment-909188034):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by csweichel** [comment]
More details: https://gitpod.slack.com/archives/C020VCB0U5A/p1630333975039400

**Comment by corneliusludmann** [comment]
Related: https://github.com/gitpod-io/gitpod/issues/5017

I have the same problem in all of my workspaces.

**Comment by broopdias** [comment]
Looking forward to see this issue fixed.
I have the same problem in all of my workspaces.

**Comment by corneliusludmann** [comment]
By the way: Independent from Gitpod, I see the same behavior in the GCP Cloud Shell (e.g. when in the Google Cloud Platform Console when I go to SQL and select Open Cloud Shell). I don't have it when I connect to a node (via the SSH button in the Google Cloud Platform Console).

**Comment by akosyakov** [comment]
We can reproduce this issue with any application embedding xterm: https://github.com/xtermjs/xterm.js/issues/3459

@broopdias could you try https://github.com/gitpod-io/gitpod/issues/5017#issuecomment-889428853 as a work around?

**Comment by akosyakov** [comment]
I removed it from in progress, since it is upstream issues in Chromium. Please follow https://bugs.chromium.org/p/chromium/issues/detail?id=1245196&q=keyboard%20french&can=2

**Comment by davidwindell** [comment]
This has been resolved in Chromium 95+ as per https://github.com/xtermjs/xterm.js/issues/3459#issuecomment-947505784

**Comment by etienne1911** [comment]
Doesn't seems to be the case, I'm using chromium 96 on linux and still have the issue.
Unable to use any common shortcuts such as ctrl-z, ctrl-/, ctrl-a. This bug is really annoying...
