### ISSUE TITLE
[code] source maps should be available for production build

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6456]

**Comment by filiptronicek** [comment]
Should be fixed by https://github.com/gitpod-io/openvscode-server/commit/e4d6a7096cc60a9fc1c187197edf7a61c9e0bdae.

**Comment by akosyakov** [comment]
Unfortunately it is still not the case in VS Code Insiders, although changes are there.

Could you please provide steps which you run locally to create distributable and verify source maps?

**Comment by akosyakov** [comment]
It does not seem that js.map are bundled:
<img width="616" alt="Screenshot 2021-11-02 at 08 40 20" src="https://user-images.githubusercontent.com/3082655/139805228-e485d898-2f59-41cd-908c-6a883d368f65.png">

I think we should adjust web gulp scripts to include them.

**Comment by jeanp413** [comment]
Fixed this in https://github.com/gitpod-io/openvscode-server/commit/24af6001623c1be73fd36c98c55b42e292af28fb. Please test it in tomorrow's insiders

**Comment by akosyakov** [comment]
It works thanks
