### ISSUE TITLE
Oh, no! Something went wrong! OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2576980378, used: 65006469130, capacity: 66388008960

### ISSUE THREAD

**Issue by dkelly255** [gitpod-io/gitpod#8238]
### Bug description

Oh, no! Something went wrong!
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2576980378, used: 65006469130, capacity: 66388008960

### Steps to reproduce

Attempting to launch my existing Gitpod workspace.

### Workspace affected

https://dkelly255-djangotutorial-quxbwl9i55a.ws-eu32.gitpod.io/

### Expected behavior

Have my existing Gitpod workspace launch without any errors.

### Example repository

Receiving error on both of these repositories:

https://dkelly255-djangotutorial-quxbwl9i55a.ws-eu32.gitpod.io/

https://dkelly255-4antasyootball-x5dfnf9rm5f.ws-eu32.gitpod.io/

### Anything else?

Receiving error on both of these repositories:

https://dkelly255-djangotutorial-quxbwl9i55a.ws-eu32.gitpod.io/

https://dkelly255-4antasyootball-x5dfnf9rm5f.ws-eu32.gitpod.io/

**Comment by pawlean** [comment]
Hey @dkelly255! We have an ongoing incident: https://www.gitpodstatus.com/incidents/6hc6n6zdkhnt 

Hang tight 👍🏼

**Comment by dkelly255** [comment]
Hi,
I am still getting the same error – I have tried restarting my machine, and it happens when I try to open either workspace as of 10:34am:

***@***.***

**Comment by mjjstockman** [comment]
Same for me on https://gitpod.io/start/#mjjstockman-setlistshare-nee26x1ripa

**Comment by dkelly255** [comment]
Note - rebuilding the workspace has allowed me to access again (I am still receiving the original error when trying to open the original workspaces) - so maybe a note should be added to the solution that folks need to rebuild their workspace to resolve? I had to reinstall the dependencies & applications after rebuilding the workspaces also and am hoping there will not be any issues or conflicts when git adding, git committing and/or git pushing to the new workspace

**Comment by pawlean** [comment]
Hi folks! This issue seems to have been resolved now. If you are experiencing any other issues, feel free to comment here. 🙏🏼 Thank you all for the support!

**Comment by mjjstockman** [comment]
Hi pawlean!
I still can't open my workspace https://gitpod.io/start/#mjjstockman-setlistshare-nee26x1ripa

**Comment by Matte-gtr** [comment]
Mine has done the same. https://gitpod.io/start/?not_found=true#pink-ostrich-p4sqvwjd

**Comment by princerachit** [comment]
I am reopening this as the issue doesn't seem to be resolved yet.

**Comment by princerachit** [comment]
I found in the log that one of the workspaces which faced this issue[ had error message](https://cloudlogging.app.goo.gl/LL1KmFJsvSvjLq7i7) saying, "ran to completion". This means that our condition check is incorrect here
https://github.com/gitpod-io/gitpod/blob/f41c652a8416540a8f6df41d70bfc8db60eb47c3/components/ws-manager/pkg/manager/manager.go#L294-L314

We should have retry mecahnism if pod failed and had an `outof` reason as failure.

**Comment by princerachit** [comment]
Julian also reported OOM issue, this was because [finalizer could not be removed](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-02-22T10:30:46Z;query=%22gitpodio-website-n%22%0Atimestamp%3D%222022-02-22T10:30:46Z%22%0AinsertId%3D%226eba3b0rwgirboyf%22?project=workspace-clusters)
```
gitpodio-website-n04y4rk4qdq
ws-51b4ada5-c357-48a1-ab75-b03b5344ed06
```

**Comment by CyriacBr** [comment]
I've had the same issue since 8+ hours now. Is there anything us users can do?
https://www.gitpodstatus.com/ shows that all services are operational. Does that mean that this issue only impact very few workspaces? Can Gitpod support solve the issue at the workspace level?

**Comment by sagor999** [comment]
Just to update. We are working on a fix, and planning to release new version later this week. :pray:

**Comment by sagor999** [comment]
Re-opening for now until we can confirm that OOM is fixed.

**Comment by ivelin** [comment]
This issue persists. Got this message today:
https://discord.com/channels/816244985187008514/946790336271876126/946791517622775858

![Screen Shot 2022-02-25 at 9 24 54 AM](https://user-images.githubusercontent.com/2234901/155742692-e27d1653-ca56-4fb1-9457-4fced0f0f7b3.png)

**Comment by sagor999** [comment]
We made another fix today and will monitor once it rolls out to production next week.
Previous fixes already reduced frequency of this happening, but it is not yet fully resolved. :(

**Comment by CyriacBr** [comment]
Not sure if the fix shipped yet but I'm personally still facing that issue.

**Comment by sagor999** [comment]
It was not deployed yet into production. :( 
It will be deployed later this week though. :pray:

**Comment by kylos101** [comment]
Hey there @CyriacBr, we shipped a fix for this issue on March 9th, therefore I am going to close this issue.

Please let us know if it's still a problem? We are happy to reopen if it's still a pain point.
