### ISSUE TITLE
When pod hits ephemeral storage limit, it just shuts down without reason provided to the user

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#8584]
### Bug description

When pod hits ephemeral storage limit, it just gets evicted by kubelet, and user might lose any unsaved work due to that. 
We don't have any way to warn a user when they are approaching the limit.
And we do not provide a clear reason for workspace shutdown when this happens.

It is also would be great if we could provide a user information regarding which folder used the most ephemeral storage to make it easier for user to fix this on their own (for example when build system outputs large amount of data, etc)

When this happens, as a user, you usually see an error like (this was done from an empty Gitpod, see repro steps below):
![image](https://user-images.githubusercontent.com/1272076/214171435-7c01ce3c-0b22-4fbe-8e77-0ec68a7c9d0b.png)

### Steps to reproduce

Try in an [empty Gitpod](https://gitpod.io/#https://github.com/gitpod-io/empty), and then a [Gitpod from Gitpod](https://gitpod.io/#https://github.com/gitpod-io/gitpod).

`fallocate -l 25G /var/tmp/test1`

The command ☝ does not reliably produce the above error. Sometimes there is no error, and the user sees that the workspace stopped (this was done via Gitpod from Gitpod):

![Image](https://user-images.githubusercontent.com/1272076/214173570-7c63b442-b99b-49cb-b837-96c38a34feb6.png)

### Expected behavior

Return an error which links to a document that details ephemeral storage limit considerations by workspace-class. For example, consider updating https://www.gitpod.io/docs/configure/workspaces/workspace-classes

### Anything else?

`/tmp` is not subject to the ephemeral storage limit because [it is backed by tmpfs](https://systemd.io/TEMPORARY_DIRECTORIES/) (memory and swap).

`/workspace` is backed by storage limited by the xfs file system, which prevents users from exceeding storage based on the [workspace storage associated with their workspace class.](https://www.gitpod.io/docs/configure/workspaces/workspace-classes)

Other locations on the file system that need storage (like /var/tmp/*) are backed by an ephemeral storage and have limits that vary by workspace class. For example, Standard workspaces are limited to 10Gi of ephemeral storage, Large workspaces are limited to 20Gi.

[Internal link to common runtime test](https://www.notion.so/gitpod/Common-runtime-tests-4e3b05c3b81e4ff6810572aee66ffad3#6a62fab4af5d4c9cbf4bb3fa97e0e12b)

**Comment by axonasif** [comment]
Also when you overuse RAM or CPU I guess, as that's something I've faced a few times and [a customer](https://gitpod.slack.com/archives/C01LDA27WJC/p1643122867132700?thread_ts=1643122744.132600&cid=C01LDA27WJC)

**Comment by kylos101** [comment]
Hi, this should be addressed with our next deployment, which should be later today if all goes well.

**Comment by sagor999** [comment]
@kylos101 I don't think that fix resolved this issue. It still might happen and user would still not get a proper error message to indicate why workspace was shutdown AFAIK.

**Comment by kylos101** [comment]
Hi @sagor999 , could you reopen the issue, and add expected (proposed) behavior?

**Comment by sagor999** [comment]
Certainly.
Expected behavior would be to tell user why workspace has failed.

**Comment by sagor999** [comment]
![Screenshot from 2022-05-17 13-00-06](https://user-images.githubusercontent.com/18602811/168899656-1fc184fe-154e-44b1-b03d-c28a65e67da5.png)
Seems like this is now correctly handled by IDE. Instead of crashing, you get an error for out of space now.
Closing this issue as fixed.

**Comment by axonasif** [comment]
This is also valid for a project that uses prebuilds and happens to write more than 10GB on the temporary filesystem using a `before` or `init` task. Please check the following:
- https://discord.com/channels/816244985187008514/1067060308687978536

**Comment by kylos101** [comment]
Added to our groundwork, and added supporting info to help with Breakdown
