### ISSUE TITLE
use self-hosted gitlab provider but workspace requests github raw content

### ISSUE THREAD

**Issue by LyleLaii** [gitpod-io/gitpod#8619]
### Bug description

I deploy a self-hosted gitpod instance and use a self-hosted gitlab provider,  when I create workspace get wrong like this:
![image](https://user-images.githubusercontent.com/23184705/156888477-802d0fc3-09f2-4103-a256-44c47497100b.png)

And this is my integration:
![image](https://user-images.githubusercontent.com/23184705/156888498-932df561-28d0-47cd-97c1-8cf38c722913.png)

### Steps to reproduce

I am install by gitpod-installer, version: 2022.01, and my config is here:
``` 
# gitpod.config.yaml
apiVersion: vi 
authProviders: 
  - kind: secret 
    name: gitlab 
blockNewUsers:
  enabled: false 
  passlist: [] 
certificate:
  kind: secret 
  name: https-certificates 
containerRegistry: 
  inCluster: false 
  external: 
    url: harbor
	certificate: 
	  kind: secret 
	  name: container-registry-token 
  s3storage: null 
database: 
  inCluster: true 
domain: gitpod.examble.com 
imagePullSecrets: null 
jaegeroperator: 
  inCluster: true 
kind: Full 
metadata: 
  region: gitpod 
objectstorage: 
  inCluster: true 
observability: 
  loglevel: info 
repository: harbor/gitpod/ 
workspace: 
  resources: 
    requests: 
	  cpu: "1" 
	  memory: 2Gi 
  runtime: containerdRuntimeDir: /var/lib/containerd/io.containerd.runtime.v2.task/k8s.io 
  containerdSocket: /run/containerd/containerd.sock 
  fsShiftnethod: shiftfs 
```

```
#provider
id: Gitlab
host: 10.0.12.200
protocol: https
type: GitLab
oauth:
  xxxx
```

**Comment by LyleLaii** [comment]
I see the new release 2022.02 have a PR ablout disableDefinitelyGp, I will try it. By the way, mayby should update the document release list?

**Comment by MrSimonEmms** [comment]
@LyleLaii I'd suggest regenerating your config before installing 2022.02 - Fuse support has been fixed, so we're recommending that over ShiftFS.

What do you mean by "By the way, mayby should update the document release list"?

**Comment by LyleLaii** [comment]
@MrSimonEmms  this page still show release 2022.01
https://www.gitpod.io/docs/self-hosted/latest/releases

**Comment by MrSimonEmms** [comment]
Fixed in https://github.com/gitpod-io/website/pull/1727
