### ISSUE TITLE
This repository is private - Organisation private repository

### ISSUE THREAD

**Issue by RomansBermans** [gitpod-io/gitpod#901]
Hi, I just have subscribed to the professional package via GitHub (organisation account Alta Flora) and when I am trying to access the repository via http://gitpod.io/#https://github.com/alta-flora/eva-app I am getting “This repository is private” message. I am logged in with my private account on gitpod.io that is the owner account of our GitHub organisation account.

Thanks!

**Comment by AlexTugarev** [comment]
Hi @RomansBermans, thanks for subscribing! 💯 

Please check that you have granted private repo access in https://gitpod.io/access-control/,  and – as the private repo belongs to an organization – check also the settings for the organization by following the [link](https://github.com/settings/connections/applications/484069277e293e6d2a2a) next to GitHub ![Screen Shot 2019-11-06 at 13 23 29](https://user-images.githubusercontent.com/914497/68298036-b16d9800-0098-11ea-8217-20b8b64dc6a9.png) If there is no green ✔️ next to your organization, please request that access.

**Comment by geropl** [comment]
Hi @RomansBermans,

I think I found the issue. We do not properly handle Organization-purchases atm. I fixed it on our side for your case, could you check if it works now?

**Comment by RomansBermans** [comment]
Hi @geropl Sure! Let me know when it fixed and I will check.

**Comment by RomansBermans** [comment]
> Hi @RomansBermans, thanks for subscribing! 💯
> 
> Please check that you have granted private repo access in https://gitpod.io/access-control/, and – as the private repo belongs to an organization – check also the settings for the organization by following the [link](https://github.com/settings/connections/applications/484069277e293e6d2a2a) next to GitHub ![Screen Shot 2019-11-06 at 13 23 29](https://user-images.githubusercontent.com/914497/68298036-b16d9800-0098-11ea-8217-20b8b64dc6a9.png) If there is no green ✔️ next to your organization, please request that access.

<img width="770" alt="Screenshot 2019-11-07 at 10 21 25" src="https://user-images.githubusercontent.com/358467/68376135-5f844b00-0148-11ea-8383-d3e72fde2fe8.png">

Seems all good here.

**Comment by geropl** [comment]
@RomansBermans Should be fixed now and accessing private repos should work.

**Comment by RomansBermans** [comment]
@geropl still the same problem:

<img width="990" alt="Screenshot 2019-11-07 at 13 06 54" src="https://user-images.githubusercontent.com/358467/68387814-826e2980-015f-11ea-806c-9b231fdf1882.png">

**Comment by svenefftinge** [comment]
Hi @RomansBermans,  sorry again. I've updated your subscription once more and it should really work now. (We cannot test-drive this on our side, as we don't have access to your account)

**Comment by RomansBermans** [comment]
@svenefftinge it works! Thanks a lot :D
